version: '2'
services:
  config-server:
    image: duyd/config-server
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "IAMSYMMETRIC"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "microservices"
      POSTGRES_PASSWORD: "microservices"
      POSTGRES_DB: "microservices"
  licensing-service:
    image: duyd/licensing-service
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_PORT: "8888"
      DATABASE_PORT: "5432"
      ENCRYPT_KEY: "IAMSYMMETRIC"
      PROFILE: "default"
      CONFIG_SERVER_URI: "http://config-server:8888"